tcp:
  client:
    host: 127.0.0.1
    port: 5566

logging:
  config: classpath:logback-spring.xml

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cbim
    username: root
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath*:mapper/*:xml